// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vklazxjdvomamvoxxybj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrbGF6eGpkdm9tYW12b3h4eWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzI4MzMsImV4cCI6MjA2NjYwODgzM30.ojxHgifRcBbth5LJZe-0eSQTQe45p2jtGkyM1q4PUCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);